# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 980cc36c660d8b470cda713f1eb1f48b43b784c87afa7ffc67cfac8855dcb972fa7be6496dd3b184e1255c37e1efcf1e808277044db1595b0d94a9792f1cd16e

test:
  secret_key_base: 727ce14a817700bb157af9407ff91625ac04c3e72350542512daab413ddf313645e8905871280ad8e6389abf1ac74fe6d1fd82e73353cb29d7e003f81a927e18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
